
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-4pm-1
owner: ucsb-cs156-s24
repo_name: team02-s24-4pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjkwOTg2OTAy","is_bot":false,"login":"miguel-luis9","name":""},"headRefName":"Luis-ArticlesTable","number":48,"title":"Luis articles table","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-1/pull/48"},{"author":{"id":"U_kgDOBX3XhQ","is_bot":false,"login":"phamaiden","name":""},"headRefName":"ap-HelpRequest-controller-get","number":47,"title":"Aiden - Added GET endpoint for Help Request controller","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-1/pull/47"},{"author":{"id":"U_kgDOB7yP8g","is_bot":false,"login":"RuizheJiang","name":""},"headRefName":"Ruizhe-DiningMenu","number":46,"title":"Ruizhe - create db for MenuItems","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-1/pull/46"},{"author":{"id":"U_kgDOBX3XhQ","is_bot":false,"login":"phamaiden","name":""},"headRefName":"Aiden-HelpRequest-Controller","number":45,"title":"Aiden - HelpRequest Controller GET and PUT","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-1/pull/45"},{"author":{"id":"U_kgDOBX3XhQ","is_bot":false,"login":"phamaiden","name":""},"headRefName":"Aiden-HelpRequest-create-db","number":43,"title":"Ap - created database table for help requests","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-1/pull/43"}]
